### ISSUE TITLE
Build fails: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MSVC', src\libcore\result.rs:906:4

### ISSUE THREAD

**Issue by AndreKR** [meh/rust-ffmpeg-sys#60]
I just added `ffmpeg-sys = "3.4.0"` to my Cargo.toml and rebuilt.

I'm new to Rust, so I might be missing something obvious.

```
   Compiling ffmpeg-sys v3.4.0
error: failed to run custom build command for `ffmpeg-sys v3.4.0`
process didn't exit successfully: `C:\dev-projects\rust-test\ffmpegtest\target\debug\build\ffmpeg-sys-9ea514c47ef9da6b\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MSVC', src\libcore\result.rs:906:4
stack backtrace:
   0:        0x1405bb681 - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:92
   1:        0x1405c692c - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:380
   2:        0x1405c6615 - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:397
   3:        0x1405c6f05 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:577
   4:        0x1405c6d98 - std::panicking::begin_panic<alloc::string::String>
                               at C:\projects\rust\src\libstd\panicking.rs:538
   5:        0x1405c6c71 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:522
   6:        0x1405c6bdf - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:498
   7:        0x1405d056e - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:71
   8:        0x13fc78ea4 - core::result::unwrap_failed<pkg_config::Error>
                               at C:\projects\rust\src\libcore\macros.rs:23
   9:        0x13fc77842 - core::result::Result<pkg_config::Library, pkg_config::Error>::unwrap<pkg_config::Library,pkg_config::Error>
                               at C:\projects\rust\src\libcore\result.rs:772
  10:        0x13fc514b5 - build_script_build::main
                               at c:\dev\rust\cargo\registry\src\github.com-1ecc6299db9ec823\ffmpeg-sys-3.4.0\build.rs:517
  11:        0x1405c8281 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:99
  12:        0x1405c7721 - std::rt::lang_start
                               at C:\projects\rust\src\libstd\rt.rs:52
  13:        0x13fc58866 - main
  14:        0x1405d7d28 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  15:         0x775b59cc - BaseThreadInitThunk

```

**Comment by retrry** [comment]
Do you have clang available on your machine? 
Bindgen requires it: https://rust-lang-nursery.github.io/rust-bindgen/requirements.html

**Comment by sylveon** [comment]
Can repro here, clang is installed
